name: RSS Feed to Readme

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_feeds:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://weyprecht.de/feed/
          readme-section: feed
          empty-commits: false
